---
- name: Setup Terraform
  hosts: localhost
  gather_facts: true
  tasks:
    - name: update apt cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: add terraform key
      become: true
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present
    - name: add terraform repo
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
        state: present
    - name: install software
      become: true
      package:
        - names:
            - docker.io
            - gnupg
            - software-properties-common
            - curl
            - terraform
    - name: add course repo
      git:
        repo: "https://github.com/theurbanpenguin/comptia-automation.git"
        dest: "{{ lookup('env', 'HOME') }}/comptia-automation"
    - name: create terraform dir
        file:
          path: "{{ lookup('env', 'HOME') }}/terraform/"
          state: directory
    - name: create web dir
        file:
          path: "{{ lookup('env', 'HOME') }}/terraform/web"
          state: directory
    - name: add main.tf
        copy:
          src: "{{ lookup('env', 'HOME') }}/comptia-automation/terraform/main.tf"
          dest: "{{ lookup('env', 'HOME') }}/terraform/main.tf"
    - name: add web content
        copy:
          dest: "{{ lookup('env', 'HOME') }}/terraform/web/index.html"
          content: This is my web page
